version: "3"

services:
  fastapi-hello:
    image: ghcr.io/7sevennights7/fastapi-hello:latest
    container_name: fastapi-hello
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://appuser:supersecret@192.168.0.155:5432/appdb
